FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Install nodemon globally
RUN npm install -g nodemon
RUN npm install nodemailer
RUN npm install --save-dev nodemailer
COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]
